### ISSUE TITLE
🚀 Roadmap

### ISSUE THREAD

**Issue by henriquesebastiao** [henriquesebastiao/modernizacao-manejo-api#71]
## Descrição

Este é um roteiro provisório, irei atualizá-lo à medida que as coisas evoluem. Algumas coisas podem ser descartadas, outras podem ser adicionadas posteriormente. É apenas uma maneira de centralizar o planejamento das funcionalidades a serem implementadas, de forma a não colocar a carroça na frente dos bois 😅.

## Roteiro

- [ ] Migrar de Poetry para [UV](https://docs.astral.sh/uv/) como gerenciador de pacotes ⚡.
- [ ] Substituir tabela employment_position por uma coluna `Enum` na tabela employment.
- [ ] Criar rota para cadastro de usuários funcionarios.
- [ ] Substituir tabela breed por uma coluna `Enum` na tabela animal.
